# Site settings
title: Anne-Laure Gros
email: your-email@domain.com
url: https://github.com/jeromelachaud/freelancer-theme
description: "Facilitatrice en Discipline Positive"
keywords: "education, bienveillance, coopération, ateliers, conférences"
phrase: "Et si on apprenait à coopérer ?"
meta_author: Gros Anne-Laure

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:


# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 5390c9 #18bc9c #80B3FF
  primary-rgb: "83,144,201" #"24,288,156" #"128,179,255"
  secondary: f6c024 #2c3e50 #FD6E8A
  secondary-dark: e47352 #233140 #A2122F
  dark: 333333

# Custom fonts
fonts: 
  sans-serif: "'Questrial', sans-serif"
  cursive: "'Just Another Hand', cursive"
  serif: "'Josefin Slab', serif"


# Contact content
contact: 
  name: Anne-Laure Gros
  phone: 06 30 91 29 80
  email: annelauredp@protonmail.com

# Footer settings
footer:
  copyright: Anne-Laure Gros
  location: Adresse
  social: Réseaux
  credits: Discipline Positive

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/annelauregrosdp/
  - title: facebook
    url: https://www.facebook.com/annelauregrosdp/


# Postal address (add as many lines as necessary) and phone number
address:
  - line: Châteaugiron (35)

# Credits content
credits: "Plus d'info sur les sites des associations de Discipline Positive française (<a href='http://www.disciplinepositive.fr/' target='_blank' rel='noopener noreferrer'>ADPF</a>) et américaine (<a href='https://positivediscipline.org/' target='_blank' rel='noopener noreferrer'>PDA</a>)."

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
